### ISSUE TITLE
cy8cproto-063-ble is not identified as either Type 1 or 2

### ISSUE THREAD

**Issue by Panometric** [Infineon/training-modustoolbox-level3-bluetooth#1]
https://github.com/search?q=repo%3AInfineon%2Ftraining-modustoolbox-level3-bluetooth%20cy8cproto-063-ble&type=code  yields 0 results

cy8cproto-063-ble is not clearly defined, nor is the underlying module CYBLE-416045-02, or CYBLE-416045-EVAL, in fact all PSoC™ 63 MCUs seems to be omitted.

**Comment by greglandry** [comment]
Hi Mike,

PSoC 63 devices fall under type 1. There are plans to update all of the exercises in the class to use a PSoC63 kit, but that work has not yet been completed.

Thanks,
Greg Landry

Cypress Semiconductor Corporation
An Infineon Technologies Company
Fellow Applications Engineer
CY CSS Integration
Office: +1 737-268-0345
***@***.******@***.***>

From: Mike Mitchell ***@***.***>
Sent: Wednesday, August 30, 2023 9:09 PM
To: Infineon/training-modustoolbox-level3-bluetooth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Infineon/training-modustoolbox-level3-bluetooth] cy8cproto-063-ble is not identified as either Type 1 or 2 (Issue #1)

Caution: This e-mail originated outside Infineon Technologies. Do not click on links or open attachments unless you validate it is safe<https://intranet-content.infineon.com/explore/aboutinfineon/rules/informationsecurity/ug/SocialEngineering/Pages/SocialEngineeringElements_en.aspx>.



https://github.com/search?q=repo%3AInfineon%2Ftraining-modustoolbox-level3-bluetooth%20cy8cproto-063-ble&type=code yields 0 results

cy8cproto-063-ble is not clearly defined, nor is the underlying module CYBLE-416045-02, or CYBLE-416045-EVAL, in fact all PSoC™ 63 MCUs seems to be omitted.
